2016-11-13 23:36:32,172 [WARNING] django.request: Not Found: /admin/packagedeals/packagedeal/packagedeals/headers/15055642_10153813774332101_159260350940143519_n.jpg/change/
2016-11-13 23:36:34,312 [WARNING] django.request: Not Found: /admin/packagedeals/packagedeal/packagedeals/headers/15055642_10153813774332101_159260350940143519_n.jpg/change/
2016-11-13 23:37:45,418 [WARNING] django.request: Not Found: /admin/packagedeals/packagedeal/packagedeals/headers/15055642_10153813774332101_159260350940143519_n.jpg/change/
2016-11-13 23:38:11,635 [WARNING] django.request: Not Found: /admin/packagedeals/packagedeal/add/packagedeals/headers/pin_location.png/change/
2016-11-13 23:38:19,159 [WARNING] django.request: Not Found: /admin/packagedeals/packagedeal/packagedeals/headers/15055642_10153813774332101_159260350940143519_n.jpg/change/
2016-11-13 23:38:19,171 [WARNING] django.request: Not Found: /admin/packagedeals/packagedeal/packagedeals/headers/15055642_10153813774332101_159260350940143519_n_GMjqYHI.jpg/change/
2016-11-13 23:39:53,869 [WARNING] django.request: Not Found: /admin/packagedeals/packagedeal/packagedeals/headers/15055642_10153813774332101_159260350940143519_n.jpg/change/
2016-11-13 23:39:53,891 [WARNING] django.request: Not Found: /admin/packagedeals/packagedeal/packagedeals/headers/15055642_10153813774332101_159260350940143519_n_GMjqYHI.jpg/change/
2016-11-13 23:39:59,281 [WARNING] django.request: Not Found: /admin/packagedeals/packagedeal/add/packagedeals/headers/pin_location.png/change/
2016-11-13 23:40:07,432 [WARNING] django.request: Not Found: /Users/tormodfladby/Documents/TorgeirsArbeid/GOtuk/media/packagedeals/headers/15055642_1_ZsFYA86.jpg
2016-11-13 23:40:07,461 [WARNING] django.request: Not Found: /admin/packagedeals/packagedeal/packagedeals/headers/15055642_10153813774332101_159260350940143519_n.jpg/change/
2016-11-13 23:40:07,474 [WARNING] django.request: Not Found: /admin/packagedeals/packagedeal/packagedeals/headers/15055642_10153813774332101_159260350940143519_n_GMjqYHI.jpg/change/
2016-11-13 23:49:05,452 [WARNING] django.request: Not Found: /Users/tormodfladby/Documents/TorgeirsArbeid/GOtuk/media/packagedeals/headers/15055642_1_ZsFYA86.jpg
2016-11-13 23:49:05,485 [WARNING] django.request: Not Found: /admin/packagedeals/packagedeal/packagedeals/headers/15055642_10153813774332101_159260350940143519_n.jpg/change/
2016-11-13 23:49:05,507 [WARNING] django.request: Not Found: /admin/packagedeals/packagedeal/packagedeals/headers/15055642_10153813774332101_159260350940143519_n_GMjqYHI.jpg/change/
2016-11-13 23:50:00,757 [WARNING] django.request: Not Found: /Users/tormodfladby/Documents/TorgeirsArbeid/GOtuk/media/packagedeals/headers/15055642_1_ZsFYA86.jpg
2016-11-13 23:50:00,788 [WARNING] django.request: Not Found: /admin/packagedeals/packagedeal/packagedeals/headers/15055642_10153813774332101_159260350940143519_n.jpg/change/
2016-11-13 23:50:00,810 [WARNING] django.request: Not Found: /admin/packagedeals/packagedeal/packagedeals/headers/15055642_10153813774332101_159260350940143519_n_GMjqYHI.jpg/change/
2016-11-13 23:50:12,747 [WARNING] django.request: Not Found: /admin/packagedeals/packagedeal/add/packagedeals/headers/pin_location.png/change/
2016-11-13 23:50:20,801 [WARNING] django.request: Not Found: /Users/tormodfladby/Documents/TorgeirsArbeid/GOtuk/media/packagedeals/headers/15055642_1_YD5KjGL.jpg
2016-11-13 23:50:20,814 [WARNING] django.request: Not Found: /Users/tormodfladby/Documents/TorgeirsArbeid/GOtuk/media/packagedeals/headers/15055642_1_ZsFYA86.jpg
2016-11-13 23:50:20,835 [WARNING] django.request: Not Found: /admin/packagedeals/packagedeal/packagedeals/headers/15055642_10153813774332101_159260350940143519_n.jpg/change/
2016-11-13 23:50:20,857 [WARNING] django.request: Not Found: /admin/packagedeals/packagedeal/packagedeals/headers/15055642_10153813774332101_159260350940143519_n_GMjqYHI.jpg/change/
2016-11-13 23:52:21,379 [WARNING] django.request: Not Found: /media/default.png
2016-11-13 23:53:33,127 [WARNING] django.request: Not Found: /media/default.png
2016-11-13 23:53:33,932 [WARNING] django.request: Not Found: /media/default.png
2016-11-13 23:54:49,567 [WARNING] django.request: Not Found: /media/default.png
2016-11-13 23:54:50,255 [WARNING] django.request: Not Found: /media/default.png
2016-11-13 23:54:56,117 [WARNING] django.request: Not Found: /media/default.png
2016-11-13 23:57:56,045 [ERROR] django.request: Internal Server Error: /admin/users/customuser/5/change/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 1044, in render
    output = self.filter_expression.resolve(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 711, in resolve
    obj = self.var.resolve(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 852, in resolve
    value = self._resolve_lookup(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 915, in _resolve_lookup
    current = current()
  File "/Library/Python/2.7/site-packages/django/contrib/admin/helpers.py", line 200, in contents
    f, attr, value = lookup_field(field, obj, model_admin)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/utils.py", line 290, in lookup_field
    value = attr()
  File "/Users/tormodfladby/Documents/TorgeirsArbeid/GOtuk/users/models.py", line 240, in image_tag
    return safestring.mark_safe('<img src="%s" width="150" height="150" />' % (self.profile_pic))
NameError: global name 'safestring' is not defined
2016-11-13 23:58:28,879 [WARNING] django.request: Not Found: /admin/users/customuser/5/change/profilepics/15055642_10153813774332101_159260350940143519_n.jpg/change/
2016-11-13 23:58:28,918 [WARNING] django.request: Not Found: /admin/users/customuser/5/change/profilepics/default.png/change/
2016-11-13 23:59:14,081 [ERROR] django.request: Internal Server Error: /admin/users/customuser/5/change/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 1512, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 1467, in changeform_view
    formsets, inline_instances = self._create_formsets(request, obj, change=True)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 1799, in _create_formsets
    for FormSet, inline in self.get_formsets_with_inlines(*get_formsets_args):
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 703, in get_formsets_with_inlines
    yield inline.get_formset(request, obj), inline
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 1952, in get_formset
    return inlineformset_factory(self.parent_model, self.model, **defaults)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 1058, in inlineformset_factory
    FormSet = modelformset_factory(model, **kwargs)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 854, in modelformset_factory
    error_messages=error_messages, field_classes=field_classes)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 548, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 257, in __new__
    raise FieldError(message)
FieldError: Unknown field(s) (image_tag) specified for DriverDetails
2016-11-14 00:02:12,787 [WARNING] django.request: Not Found: /admin/users/customuser/5/change/<bound method DriverDetails.profile_pic of <DriverDetails: DriverDetails object>>/change/
2016-11-14 00:02:46,394 [WARNING] django.request: Not Found: /admin/users/customuser/5/change/<bound method DriverDetails.profile_pic of <DriverDetails: DriverDetails object>>/change/
2016-11-14 00:04:43,693 [ERROR] django.request: Internal Server Error: /admin/users/customuser/5/change/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 1512, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 1467, in changeform_view
    formsets, inline_instances = self._create_formsets(request, obj, change=True)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 1799, in _create_formsets
    for FormSet, inline in self.get_formsets_with_inlines(*get_formsets_args):
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 703, in get_formsets_with_inlines
    yield inline.get_formset(request, obj), inline
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 1952, in get_formset
    return inlineformset_factory(self.parent_model, self.model, **defaults)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 1058, in inlineformset_factory
    FormSet = modelformset_factory(model, **kwargs)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 854, in modelformset_factory
    error_messages=error_messages, field_classes=field_classes)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 548, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 257, in __new__
    raise FieldError(message)
FieldError: Unknown field(s) (profile_pic) specified for DriverDetails
2016-11-14 00:07:32,973 [ERROR] django.request: Internal Server Error: /admin/users/customuser/5/change/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 1512, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 1467, in changeform_view
    formsets, inline_instances = self._create_formsets(request, obj, change=True)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 1799, in _create_formsets
    for FormSet, inline in self.get_formsets_with_inlines(*get_formsets_args):
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 703, in get_formsets_with_inlines
    yield inline.get_formset(request, obj), inline
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 1952, in get_formset
    return inlineformset_factory(self.parent_model, self.model, **defaults)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 1058, in inlineformset_factory
    FormSet = modelformset_factory(model, **kwargs)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 854, in modelformset_factory
    error_messages=error_messages, field_classes=field_classes)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 548, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 257, in __new__
    raise FieldError(message)
FieldError: Unknown field(s) (image_tag) specified for DriverDetails
2016-11-14 00:07:38,352 [ERROR] django.request: Internal Server Error: /admin/users/customuser/5/change/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 1512, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 1467, in changeform_view
    formsets, inline_instances = self._create_formsets(request, obj, change=True)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 1799, in _create_formsets
    for FormSet, inline in self.get_formsets_with_inlines(*get_formsets_args):
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 703, in get_formsets_with_inlines
    yield inline.get_formset(request, obj), inline
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 1952, in get_formset
    return inlineformset_factory(self.parent_model, self.model, **defaults)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 1058, in inlineformset_factory
    FormSet = modelformset_factory(model, **kwargs)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 854, in modelformset_factory
    error_messages=error_messages, field_classes=field_classes)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 548, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 257, in __new__
    raise FieldError(message)
FieldError: Unknown field(s) (image_tag) specified for DriverDetails
2016-11-14 00:07:50,517 [WARNING] django.request: Not Found: /media/profilepics/default.png
2016-11-14 00:07:50,565 [WARNING] django.request: Not Found: /media/profilepics/default.png
2016-11-14 00:08:04,905 [WARNING] django.request: Not Found: /media/profilepics/default.png
2016-11-14 00:08:04,941 [WARNING] django.request: Not Found: /media/profilepics/default.png
2016-11-14 00:08:38,721 [ERROR] django.request: Internal Server Error: /admin/users/customuser/5/change/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 1512, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Library/Python/2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 1467, in changeform_view
    formsets, inline_instances = self._create_formsets(request, obj, change=True)
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 1799, in _create_formsets
    for FormSet, inline in self.get_formsets_with_inlines(*get_formsets_args):
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 703, in get_formsets_with_inlines
    yield inline.get_formset(request, obj), inline
  File "/Library/Python/2.7/site-packages/django/contrib/admin/options.py", line 1952, in get_formset
    return inlineformset_factory(self.parent_model, self.model, **defaults)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 1058, in inlineformset_factory
    FormSet = modelformset_factory(model, **kwargs)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 854, in modelformset_factory
    error_messages=error_messages, field_classes=field_classes)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 548, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "/Library/Python/2.7/site-packages/django/forms/models.py", line 257, in __new__
    raise FieldError(message)
FieldError: Unknown field(s) (image_tag) specified for DriverDetails
2016-11-14 00:10:23,983 [WARNING] django.request: Not Found: /media/profilepics/default.png
2016-11-14 00:10:24,029 [WARNING] django.request: Not Found: /media/profilepics/default.png
2016-11-14 00:10:28,354 [WARNING] django.request: Not Found: /media/packagedeals/headers/15055642_10153813774332101_159260350940143519_n.jpg
2016-11-14 00:10:28,389 [WARNING] django.request: Not Found: /media/packagedeals/headers/15055642_10153813774332101_159260350940143519_n.jpg
